config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:create, :destroy]
  get '/favorites/index', to: 'favorites#index'
  resources :pictures do
    collection do
      post :confirm
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_many :favorites, dependent: :destroy
  belongs_to :user
  mount_uploader :image, PictureImageUploader
  validates :image, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
  mount_uploader :image,UserImageUploader
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 } , on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def ensure_correct_user
    if current_user.id !=  @picture.user_id
      redirect_to pictures_path,notice: 'アクセスできません'
    end
  end
  def edit_correct_user
    if current_user.id !=  params[:id].to_i
      redirect_to new_user_path,notice: 'アクセスできません'
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorite_pictures
  end
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  def index
    @pictures = Picture.all.order(created_at: :desc)
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
  end

  def edit
  end

  def create
    @picture = current_user.pictures.build(picture_params)

    respond_to do |format|
      if @picture.save
        #PictureMailer.picture_mail(@picture).deliver
        format.html { redirect_to pictures_path, notice: '投稿しました' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to pictures_path, notice: '更新しました' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_path, notice: '削除しました' }
      format.json { head :no_content }
    end
  end

  private
  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:image,:image_cache, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update]
  before_action :authenticate_user, except: [:new, :create]
  before_action :edit_correct_user, only: [:edit, :update]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: '更新しました'
    else
      render :edit
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,:image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def authenticate_user
    if current_user == nil
      redirect_to new_session_path, notice: 'ログインが必要です'
    end
  end
end

app/views/favorites/index.html.erb
  <h1>お気に入り一覧</h1>
  <% @favorites.each do |favorite| %>
  <div class="feed">
    <%= favorite.created_at.strftime("%Y-%m-%d %H:%M") %><br><br>
    <%= favorite.user.name %><br>
    <%= image_tag favorite.image.url %><br>
    <%= favorite.content %>
  </div>
  <br><br>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-css">
      <header>
        <p class="header-logo">Instagram</p>
        <div class="header-link">
          <%= link_to '投稿一覧', pictures_path %>
          <%= link_to '新規投稿', new_picture_path %>
          <% if logged_in? %>
            <%= link_to "Profile", user_path(current_user.id) %>
            <%= link_to "Logout", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "Sign up", new_user_path %>
            <%= link_to "Login", new_session_path %>
          <% end %>
        </div>
      </header>
      <div class="wrapper">
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </div>
      <footer>
        <p>Instagram</p>
      </footer>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %><br>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %><br>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <br>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit %><br><br>
  </div>
<% end %>

app/views/pictures/_picture.html.erb
  <div class="feed">
      <%= picture.created_at.strftime("%Y-%m-%d %H:%M") %><br><br>
      <%= "User:    #{picture.user.name}   " %><br>
      <%= image_tag picture.image.url %><br>
      <%= "Content:   #{picture.content}" %><br><br>
      <%= link_to 'Show', picture,class: 'btn btn-primary' %>
      <% if current_user.id == picture[:user_id] %>
        <%= link_to 'Edit', edit_picture_path(picture),class: 'btn btn-primary' %>
        <%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-primary' %>
      <% end %>
  </div>
  <br><br><br>

app/views/pictures/confirm.html.erb
<h1>確認画面</h1>
<div class="view">
  <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <p>本文:<%= @picture.content %></p>
    <%= form.hidden_field :image_cache %>
    <%= form.hidden_field :content %>
    <%= form.submit "投稿する" %>
  <% end %>
  <%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
    <%= form.hidden_field :image_cache %>
    <%= form.hidden_field :content %><br>
    <%= form.submit "戻る", name: "back" %>
  <% end %>
</div>

app/views/pictures/edit.html.erb
<h1>投稿編集</h1>
<div class="view">
  <%= render 'form', picture: @picture %>

  <%= link_to 'Show', @picture ,class: 'btn btn-primary'%> |
  <%= link_to 'Back', pictures_path ,class: 'btn btn-primary'%>
</div>

app/views/pictures/index.html.erb
<h1>投稿一覧テスト</h1>
<%= render @pictures %>

app/views/pictures/new.html.erb
<h1>新規投稿</h1>
<div class="view">
  <%= render 'form', picture: @picture %>
  <%= link_to 'Back', pictures_path ,class: 'btn btn-primary'%>
  <br>
</div>

app/views/pictures/show.html.erb
<div class="view">
  <p>
    <strong>Image:</strong><br>
    <%= image_tag @picture.image.url %>
  </p><br>

  <p>
    <strong>Content:</strong><br>
    <%= @picture.content %>
  </p><br>
  <% unless @picture.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
  <%= link_to 'Back', pictures_path ,class: 'btn btn-primary' %>
  <% if current_user.id == @picture[:user_id] %>
    <%= link_to 'Edit', edit_picture_path(@picture),class: 'btn btn-primary'  %>
    <%= link_to 'Destroy', picture_path(@picture) , method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>
<div class="view">
  <%= render 'form' %>
  <%= form_with(model: @user, local: true) do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :email %><br>
    <%= f.email_field :email %><br><br>
    <dl id="accordion">
      <dt>パスワード変更はこちら</dt>
      <dd>
        <%= f.label :password %><br>
        <%= f.password_field :password %><br>
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %><br>
      </dd>
    </dl>
    <%= f.label :image %><br>
    <%= image_tag(@user.image.url) if @user.image && @user.image.url %><br>
    <%= f.file_field :image %><br>
    <%= f.hidden_field :image_cache %><br>

    <%= f.submit "Create my account", class: 'btn btn-primary' %>
  <% end %>
  <br>
</div>

app/views/users/new.html.erb
<h1>新規登録</h1>
<%= render 'form' %>
<div class="view">
  <%= form_with(model: @user, local: true) do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :email %><br>
    <%= f.email_field :email %><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>
    <%= f.label :image %><br>
    <%= f.file_field :image %><br>
    <%= f.submit "アカウントを作成",class: 'btn btn-primary' %><br>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<div class="view">
  <p>メールアドレス: <%= @user.email %></p>
  <%= image_tag @user.image.url %><br><br>
  <%= link_to 'お気に入り一覧', favorites_index_path ,class: 'btn btn-primary' %>
  <%= link_to 'Edit', edit_user_path(@user.id) ,class: 'btn btn-primary' %>
</div>